config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  resources :notification_contents
  root to: "documents#index"
  namespace :admin do
      resources :users
      # resources :documents
      resources :departments
      root to: "users#index"
      authenticate :user do
        mount Sidekiq::Web => '/sidekiq'
      end
  end
  namespace :api, constraints: { format: 'json' } do
    namespace :v1, constraints: { format: 'json' } do
      post 'users/login', to: "user#request_for_otp"
      post 'users/verify', to: "user#verify_otp"
      post 'users/update_device_token', to: "user#update_device_token"

      post 'create_comment', to: "api_v1#create_comment"
      get 'comments', to: "api_v1#comments"
      get 'notification_contents', to: "api_v1#notification_contents"
      scope :format => true, :constraints => { :format => 'json' } do
        resources :documents, only: [:index,:show]
      end
    end
  end 
  devise_for :users
  resources :documents
  post "document_create_comments", to: "documents#create_comments"
  post "update_web_push_token", to: "notifications#update_web_push_token", as: :update_device_token
  post "get_users_by_department", to: "departments#get_users_by_department", as: :get_users_by_department
  
  # notifications
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification_content.rb
class NotificationContent < ApplicationRecord
end

app/controllers/notification_contents_controller.rb
class NotificationContentsController < ApplicationController
  before_action :set_notification_content, only: [:show, :edit, :update, :destroy]

  # GET /notification_contents
  # GET /notification_contents.json
  def index
    if current_user.user_type == "super_admin"
      redirect_to documents_path
    # elsif current_user.user_type == "admin"
      # @notification_contents = NotificationContent.where(user_id: current_user.id).order("created_at DESC")
    else
      @notification_contents = NotificationContent.where("#{current_user.id}=ANY(user_ids)").order("created_at DESC")
    end
  end

  # GET /notification_contents/1
  # GET /notification_contents/1.json
  def show
  end

  # GET /notification_contents/new
  def new
    @notification_content = NotificationContent.new
  end

  # GET /notification_contents/1/edit
  def edit
  end

  # POST /notification_contents
  # POST /notification_contents.json
  def create
    @notification_content = NotificationContent.new(notification_content_params)

    respond_to do |format|
      if @notification_content.save
        format.html { redirect_to @notification_content, notice: 'Notification content was successfully created.' }
        format.json { render :show, status: :created, location: @notification_content }
      else
        format.html { render :new }
        format.json { render json: @notification_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notification_contents/1
  # PATCH/PUT /notification_contents/1.json
  def update
    respond_to do |format|
      if @notification_content.update(notification_content_params)
        format.html { redirect_to @notification_content, notice: 'Notification content was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification_content }
      else
        format.html { render :edit }
        format.json { render json: @notification_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notification_contents/1
  # DELETE /notification_contents/1.json
  def destroy
    @notification_content.destroy
    respond_to do |format|
      format.html { redirect_to notification_contents_url, notice: 'Notification content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification_content
      @notification_content = NotificationContent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notification_content_params
      params.require(:notification_content).permit(:noti_message, :details_id, user_ids: [])
    end
end

app/helpers/notification_contents_helper.rb
module NotificationContentsHelper
end

app/views/notification_contents/_form.html.erb
<%= simple_form_for(@notification_content) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :noti_message %>
    <%= f.input :details_id %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notification_contents/edit.html.erb
<h1>Editing Notification Content</h1>

<%= render 'form', notification_content: @notification_content %>

<%= link_to 'Show', @notification_content %> |
<%= link_to 'Back', notification_contents_path %>

app/views/notification_contents/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">ခေါင်းစဉ်</th>
      <th scope="col">စာအမှတ်</th>
      <th scope="col">အကြောင်းကြားခဲ့သည့်နေ့စွဲ</th>
    </tr>
  </thead>
  <tbody>
    <% @notification_contents.each do |notification_content| %>
      <% if Document.exists?(notification_content.details_id) %>
        <tr scope="row">
          <td><%= notification_content.noti_message %></td>
          <td><%= link_to Document.find(notification_content.details_id).document_no.to_s.to_mm, document_path(Document.find(notification_content.details_id)), class: "document_no" %></td>
          <td><%= notification_content.created_at.strftime("%d-%m-%Y") %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/notification_contents/new.html.erb
<h1>New Notification Content</h1>

<%= render 'form', notification_content: @notification_content %>

<%= link_to 'Back', notification_contents_path %>

app/views/notification_contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Noti message:</strong>
  <%= @notification_content.noti_message %>
</p>

<p>
  <strong>Details:</strong>
  <%= @notification_content.details_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @notification_content.user_id %>
</p>

<%= link_to 'Edit', edit_notification_content_path(@notification_content) %> |
<%= link_to 'Back', notification_contents_path %>