config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  resources :notification_contents
  root to: "documents#index"
  namespace :admin do
      resources :users
      # resources :documents
      resources :departments
      root to: "users#index"
      authenticate :user do
        mount Sidekiq::Web => '/sidekiq'
      end
  end
  namespace :api, constraints: { format: 'json' } do
    namespace :v1, constraints: { format: 'json' } do
      post 'users/login', to: "user#request_for_otp"
      post 'users/verify', to: "user#verify_otp"
      post 'users/update_device_token', to: "user#update_device_token"

      post 'create_comment', to: "api_v1#create_comment"
      get 'comments', to: "api_v1#comments"
      get 'notification_contents', to: "api_v1#notification_contents"
      scope :format => true, :constraints => { :format => 'json' } do
        resources :documents, only: [:index,:show]
      end
    end
  end 
  devise_for :users
  resources :documents
  post "document_create_comments", to: "documents#create_comments"
  post "update_web_push_token", to: "notifications#update_web_push_token", as: :update_device_token
  post "get_users_by_department", to: "departments#get_users_by_department", as: :get_users_by_department
  
  # notifications
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
  has_many_attached :attachment
  acts_as_commentable
  before_create :generate_fields
  before_save :copy_reference_division

  has_many :user_documents, :dependent => :destroy
  has_many :users, through: :user_documents

  def copy_reference_division
    self.reference_division = self.destination_department
  end 


  def reference_string
    reference_division.to_s + reference_document_no.to_s
  end
  def generate_fields
    if Document.count > 0 
      self.document_no = Document.last.document_no + 1
      # if self.document_no < 9000
      #   self.document_no = Document.last.document_no + 9001
      # end
    else
      # self.document_no = 1
      self.document_no = 15500
    end

    self.document_date = Date.today
  end
end

app/controllers/admin/documents_controller.rb
module Admin
  class DocumentsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/v1/documents_controller.rb
class Api::V1::DocumentsController < Api::V1::ApiV1Controller
  
  
  before_action :set_user, :set_headers, :except => [:request_for_otp, :verify_otp]
  
  before_action :set_api_v1_document, only: [:show, :edit, :update, :destroy]
  before_action :check_authorized_editor, only: [:show]

  # GET /api/v1/documents
  # GET /api/v1/documents.json
  def index
    @api_v1_documents = Document.all
  end

  # GET /api/v1/documents/1
  # GET /api/v1/documents/1.json
  def show
  end

  # GET /api/v1/documents/new
  def new
    @api_v1_document = Document.new
  end

  # GET /api/v1/documents/1/edit
  def edit
  end

  # POST /api/v1/documents
  # POST /api/v1/documents.json
  def create
    @api_v1_document = Document.new(api_v1_document_params)

    respond_to do |format|
      if @api_v1_document.save
        format.html { redirect_to @api_v1_document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @api_v1_document }
      else
        format.html { render :new }
        format.json { render json: @api_v1_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api/v1/documents/1
  # PATCH/PUT /api/v1/documents/1.json
  def update
    respond_to do |format|
      if @api_v1_document.update(api_v1_document_params)
        format.html { redirect_to @api_v1_document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @api_v1_document }
      else
        format.html { render :edit }
        format.json { render json: @api_v1_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api/v1/documents/1
  # DELETE /api/v1/documents/1.json
  def destroy
    @api_v1_document.destroy
    respond_to do |format|
      format.html { redirect_to api_v1_documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api_v1_document
      @api_v1_document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def api_v1_document_params
      params.fetch(:api_v1_document, {})
    end

    def check_authorized_editor
      if params[:id].present?
        if @current_user.is_normal_user? && !@api_v1_document.user_ids.include?(@current_user.id)
          render :json => failureJson(jresponse(:bad_request),nil, "You are not authorized.") and return
        end
      else
        render :json => failureJson(jresponse(:bad_request),nil, "You are not authorized.") and return
      end
    end 
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include NotificationSender
  before_action :authenticate_user!
  before_action :set_document, only: [:show, :edit, :update, :destroy, :create_comments]
  before_action :check_authorized_editor, except: [:index, :new, :create]
  before_action :check_document_created_user, only: [:edit]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all.order(created_at: :desc)
    @documents_json = DocumentSerializer.new(@documents, params: {current_user: current_user } ).serialized_json
  end

  def create_comments
    @document = Document.find(params[:comment][:document_id])
    comment = @document.comments.create

    comment.title = params[:comment][:title]
    comment.comment = params[:comment][:comment]
    comment.user_id = current_user.id
    comment.save

    if @document.comments.map{|x| User.find(x.user_id).user_type}.include?("admin")
      admin_mobile_registration_ids = []
      @document.comments.map{|x| admin_mobile_registration_ids << User.find(x.user_id) if User.find(x.user_id).user_type == "admin" && User.find(x.user_id) != current_user.id}

      mobile_registration_ids = admin_mobile_registration_ids.uniq.pluck(:mobile_device_token) + (@document.users.pluck(:mobile_device_token) - [current_user.mobile_device_token])
      web_push_registration_ids = admin_mobile_registration_ids.uniq.pluck(:web_push_token) + (@document.users.pluck(:web_push_token) - [current_user.web_push_token])
    else
      mobile_registration_ids = (@document.users.pluck(:mobile_device_token) - [current_user.mobile_device_token])
      web_push_registration_ids = (@document.users.pluck(:web_push_token) - [current_user.web_push_token])
    end
    # mobile_registration_ids = User.get_admin().pluck(:mobile_device_token) + (@document.users.pluck(:mobile_device_token) - [current_user.mobile_device_token])
    
    # web_push_registration_ids = User.get_admin().pluck(:web_push_token) + (@document.users.pluck(:web_push_token) - [current_user.web_push_token])
    

    message = "#{current_user.name} commented on document number #{@document.document_no}"

    send_fcm_push_notification(message, mobile_registration_ids, @document.id, 'comment')
    send_fcm_push_notification(message, web_push_registration_ids, @document.id, 'comment')
    # NotificationContent.create(noti_message: message, details_id: @document.id, user_ids: @document.created_user)
    @notification_content = NotificationContent.new
    @notification_content.noti_message = message
    @notification_content.details_id = @document.id
    # @notification_content.user_ids = @notification_content.user_ids << [@document.created_user] - [current_user.id]
    # @notification_content.user_ids = @notification_content.user_ids << @document.created_user
    @notification_content.user_ids << @document.created_user
    @notification_content.user_ids << @document.comments.last(2).first.user_id
    @notification_content.user_ids = @notification_content.user_ids - [@current_user.id]
    @notification_content.save
    redirect_to @document,  notice: 'Comment was successfully created.'
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    if current_user.is_normal_user? && !@document.user_ids.include?(current_user.id)
      @document.user_ids = @document.user_ids << current_user.id
    end

    respond_to do |format|
      if @document.save
        mobile_registration_ids = @document.users.pluck(:mobile_device_token) - [current_user.mobile_device_token]
        web_push_registration_ids = @document.users.pluck(:web_push_token) - [current_user.web_push_token]
        message = "#{current_user.name} created a new document ( No-#{@document.document_no} )"
        
        

        send_fcm_push_notification(message, mobile_registration_ids, @document.id, "new_document")
        send_fcm_push_notification(message, web_push_registration_ids, @document.id, "new_document")

        NotificationContent.create(noti_message: message, details_id: @document.id, user_ids: @document.user_ids - [current_user.id])

        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        if current_user.is_normal_user? && !@document.user_ids.include?(current_user.id)
          @document.user_ids = @document.user_ids << current_user.id
        end
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def check_authorized_editor
      @document = Document.find(params[:comment][:document_id]) if params[:comment].present?
      if current_user.is_normal_user? && !@document.user_ids.include?(current_user.id)
      # if @document.created_user != current_user.id
        redirect_to root_path
      end
    end 

    def set_document
      @document = Document.find(params[:id]) if params[:id].present?
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:document_date, :document_no, :division, :sub_division, :reference_document_no, :destination_department, :subject,  :working_status, :reference_division, :created_user, attachment: [], user_ids: [])
    end

    # def notification_content_params
    #   params.require(:notification_content).permit(:noti_message, :details_id, user_ids: [])
    # end

    def check_document_created_user
      if @document.created_user != current_user.id
        redirect_to root_path
      end
    end
end

app/helpers/api/v1/documents_helper.rb
module Api::V1::DocumentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= simple_form_for(document, local: true) do |form| %>
    <% if document.errors.any? %>
	<div id="error_explanation">
	    <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

	    <ul>
		<% document.errors.full_messages.each do |message| %>
		    <li><%= message %></li>
		<% end %>
	    </ul>
	</div>
    <% end %>
    <div class="field"  data-controller="auto-complete"  data-auto-complete-id="#document_sub_division" data-auto-complete-type="subdivision">
	    <%= form.input :sub_division, label: "ဌာနခွဲ" %>
    </div>    

    <div class="field">
        <%#= form.input :destination_department, :collection => ['MoE','DHE','DERPT', 'DMNE(Research)', 'DMNE(Education)', 'DTVET', 'DRI', 'DAE', 'DME', 'Dept of Ethic Language', 'Other Ministries or Departments'], label: "ပေးပို့မည့်ဌာန" %>
    </div>

    <div class="form-group field">
        <label class="string optional" for="document_destination_department">ပေးပို့မည့်ဌာန</label>
        <input list="country" name="document[destination_department]" class="form-control string optional" >
        <datalist id="country">
            <option value="MoE">
            <option value="DHE">
            <option value="DERPT">
            <option value="DMNE(Research)">
            <option value="DMNE(Education)">
            <option value="DTVET">
            <option value="DRI">
            <option value="DAE">
            <option value="DME">
            <option value="Dept of Ethic Language">
            <option value="Other Ministries or Departments">
        </datalist>
    </div>

    <div class="field">
	<%= form.input :subject, label: "အကြောင်းအရာ"	%>
    </div>

    <div class="field">
	    <%= form.input :working_status, label: "ဆောင်ရွက်နေသည့်အခြေအနေ"	%>
    </div>

    <div class="field">
	    <%= form.input :division, label: "ဖိုင်အမည်"	%>
    </div>
    
    <div data-controller="dependent-user-select" data-dependent-user-select-document-id="<%= @document.id.present? ? @document.id : 0 %>">
        <div class="field">
            <%= simple_fields_for :other do |o| %>
                <%= o.input :departments, :collection => Department.all, :label_method => :name, :value_method => :id, input_html: { multiple: true,:data => {:target => 'dependent-user-select.departmentSelect', :action => "dependent-user-select#handleSelectChange"}  } %>
            <% end %>
        </div>

        <div class="field">
            <%= form.association :users, :collection => User.where.not(:user_type => ['admin', 'super_admin']).where.not(id: current_user.id), :label_method => :name, :value_method => :id, :selected => current_user.id, input_html: {:data => {:target => 'dependent-user-select.userSelect'} } %>
        </div>
        
    </div>

    <div class="field">
        <%#= form.input :reference_division, label: "ရည်ညွှန်းစာဌာန"	%>
        <%= form.input :reference_document_no, label: "ရည်ညွှန်းစာအမှတ်"	%>
    </div>
    
    <div class="field">
        <%= form.hidden_field :created_user, value: current_user.id %>
    </div>


    <div class="actions">
	<%= form.submit "Save", class: "btn btn-success" %>
    </div>
<% end %>

app/views/documents/edit.html.erb
<div class="col-md-8 offset-md-2">
    <h4>Editing Document</h4>
    <hr>
    <%= render 'form', document: @document %>
    <%= link_to 'Show', @document, class: "btn btn-info mb-3 mt-3"  %> |
    <%= link_to 'Back', documents_path, class: "btn btn-info mb-3 mt-3"  %>
</div>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>
<% unless current_user.user_type == "viewer" %>
    <%# if mobile_device? %>
    <% if false %>
	<a href="<%= new_document_path %>" class="mdc-fab stick-bottom" aria-label="New">
	    <div class="mdc-fab__ripple"></div>
	    <span class="mdc-fab__icon material-icons">add</span>
	</a>
    <% end %>
    <%# else %>
	    <%= link_to 'New Document', new_document_path, class: "btn btn-success mb-3" %>
    <%# end %>
<% end %>
<%= render partial: "shared/documents_grid", locals:{ documents: @documents_json }  %>
<br>

<style>
 .table .bg-yellow th{
     background-color: #ffff1f;
     color: black;
 }
 .table .bg-green th{
     background-color: green;
 }

 <% if mobile_device? %>
 a:hover {
     color: #FFFFFF;
     text-decoration: none;
 }
 .stick-bottom{
     position: absolute;
     right: 10%;
     bottom: 10%;
 }
 <% end %>
</style>

app/views/documents/new.html.erb
<div class="col-md-8 offset-md-2">
    <h4>New Document</h4>
    <hr>
    <%= render 'form', document: @document %>
    <%= link_to 'Back', documents_path, class: "btn btn-info mb-3 mt-3" %>
</div>

app/views/documents/show.html.erb
<div class="row">
<div class="col-md-8 offset-md-2">
<h5>
    <b>
	အခြေခံပညာဦးစီးဌာန၏ ညှိနှိုင်းစာနှင့် တင်ပြစာ
    </b>
</h5>

<table class="table mt-4 table-responsive-sm table-responsive-xs table-striped">
    <tr>
	<th>
	    စဥ်
	</th>
	<td>
	    <%= @document.id.to_s.to_mm %>
	</td>
    </tr>
    <tr>
	<th>
	    ရက်စွဲ

	</th>
	<td>
	    <%= @document.document_date.to_s.to_mm %>
	</td>
    </tr>
    <tr>
	<th>
	    စာအမှတ်

	</th>
	<td class="document_no">
	    <%= @document.document_no.to_s.to_mm %>
	</td>
    </tr>
    <tr>
	<th>
	    ဌာနခွဲ
	</th>
	<td>
	    <%= @document.sub_division %>
	</td>
    </tr>
    <tr>
	<th>
	    ပေးပို့မည့်ဌာန

	</th>
	<td>
	    <%= @document.destination_department %>
	</td>
    </tr>

    <tr>
	<th>
	    အကြောင်းအရာ
	</th>
	<td>
	    <%= @document.subject %>
	</td>
    </tr>
    <tr>
	<th>
	    ပူးတွဲ
	</th>
	<td>
		<% if @document.attachment.attachments.present? %>
			<% @document.attachment.attachments.each do |attachment| %>
				<span style="margin-right: 7px;"><%= link_to  "attachment",attachment, target: :_blank %></span>
			<% end %>
	  <% end %>
	</td>
    </tr>
    <tr>
	<th>
	    ဆောင်ရွက်နေသည့်အခြေအနေ
	</th>
	<td>
	    <%= @document.working_status %>
	</td>
    </tr>
    <tr>
	<th>
	    ဖိုင်အမည်
	</th>
	<td>
	    <%= @document.division %>
	</td>
    </tr>
    <tr>
	<th>
	    ရည်ညွှန်းစာအမှတ်

	</th>
	<td>
	    <%= @document.reference_document_no%>
	</td>
	</tr>
	<tr>
	<th>
		ရည်ညွှန်းစာဌာန

	</th>
	<td>
	    <%= @document.reference_division%>
	</td>
    </tr>

</table>

	<%= simple_form_for(@document, local: true) do |form| %>
		<% if @document.created_user == current_user.id %>

			<div class="field">
				<%= form.input :attachment, as: :file, required: true, input_html: { multiple: true}, id: "attachment" %>
			</div>

			<% unless current_user.user_type == "viewer" %>
					<%= link_to 'Edit', edit_document_path(@document),class: "btn btn-warning" %> |
		
						<%= form.submit "Done", class: "btn btn-info submit-btn"  %> |
					
			<% end %>	
		<% end %>
				<%= link_to 'Home Page', documents_path, class: "btn btn-success" %>
	<% end %>


    <hr/>
    <h4><b> Comments</b> </h4>
    <% unless current_user.user_type == "viewer" %>
	<%= simple_form_for(Comment.new, local: true,url: document_create_comments_path) do |form| %>
	    <div class="field mt-3">
		<div class="row">
		    <%= form.hidden_field "document_id", value: @document.id %>

		    
		    <div class="col-6">
			<%= form.input :title %>
		    </div>
		    <div class="col-3">
		    </div>

		    <div class="col-6">
			<%= form.input :comment %>
		    </div>
		    <div class="col-12 mb-3">
			<%= form.submit class: "btn btn-success" %>
	    </div>
	</div>
    </div>
<% end %>
<% end %>
<hr>
<div class="mt-3 mb-3">
<%  @document.comments.each do |comment| %>
    <div class="card mt-3">
	<h5 class="card-header"><%= comment.user.present? ? comment.user.name : "" %> commented	<span class="float-right"><%= time_ago_in_words(comment.created_at) %></span> </h5>

	<div class="card-body">
	    <h5 class="card-title"><%= comment.title %></h5>
		<p class="card-text"><%= comment.comment %></p>

	</div>
    </div>    


<% end %>
</div>
</div>
</div>